name: Test Scripts

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'scripts/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'scripts/**'

jobs:
  test-debian:
    name: Test on Debian 12
    runs-on: ubuntu-latest
    container:
      image: debian:12
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          apt-get update -qq
          apt-get install -y shellcheck
      
      - name: Run ShellCheck on update-check.sh
        run: shellcheck scripts/update-check.sh
      
      - name: Run ShellCheck on server-update.sh
        run: shellcheck scripts/server-update.sh
      
      - name: Test script syntax
        run: |
          bash -n scripts/update-check.sh
          bash -n scripts/server-update.sh
      
      - name: Test update-check.sh execution
        run: |
          # Dry run test (requires root in real environment)
          bash scripts/update-check.sh || echo "Script requires system privileges"

  test-ubuntu:
    name: Test on Ubuntu 22.04
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      
      - name: Run ShellCheck
        run: |
          shellcheck scripts/update-check.sh
          shellcheck scripts/server-update.sh
      
      - name: Test script syntax
        run: |
          bash -n scripts/update-check.sh
          bash -n scripts/server-update.sh
